#!/bin/bash
if [ "$1" = "-V" ]; then
  echo "mypy 1.11.2 (compiled: yes)"
else
  last2="${*:$#-1}"
  my_dir=$(dirname "$0")
  expected_args="--show-column-numbers --show-absolute-path --output json --config-file $my_dir/mypy.ini --shadow-file /src/a.py $last2"
  if [ "$*" != "$expected_args" ]; then
    echo "expected: $expected_args"
    echo "received: $*"
    exit 1
  fi
  last="${*:$#}"
  filename=$(basename "$last")
  # Let's extract original filename from temp file's name, e.g. pycharm_mypy_15708631520625806318_d.py -> d.py
  filename="${filename/pycharm_mypy_/}"
  filename="${filename//[0-9]/}"
  filename="${filename/_/}"
  cat "$0_${filename}_result.json"
fi